### PR TITLE
[WIP] Swift 3.0 / Xcode 8 Support

### PR DESCRIPTION
**Pull request by liscio**
_Note_: This probably shouldn't be merged until either Xcode 8 ships, or you want to maintain a separate swift3 branch in the meantime.

I had to noodle around with the code only very little to get this all working with the latest Xcode beta and Swift 3, which is nice. Tests all pass so far, so it should be good to go. I'll start consuming this in a Swift 3 project I started recently to see how it holds up in use.

### CODE REVIEW

**Comment by younata** [comment]
Oh, sweet. Thanks.

I'll merge this after Xcode 8 ships.

**Comment by younata** [comment]
This looks mostly good to go. Just want to wait until quick merges their swift-3.0 branch into master.

**Comment by liscio** [comment]
@younata All updated & ready to go. Builds fine w/ the Xcode 8.1 GM (8B62), and works w/ my other projects.

**Comment by younata** [comment]
Manually merged. Thanks!

**Pull request closed without merging**
